spring:
  datasource:
    url: jdbc:mysql://localhost:3306/uces_web2
    username: root
    password: sebamysql
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
       cache: false
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  